const express = require('express')
const router = express.Router()
const usuarioController = require('../controllers/usuarioController')
const saudeController = require('../controllers/saudeController')
const natacaoController = require('../controllers/natacaoController')

router.get('/', usuarioController.listar)
router.get('/:id', usuarioController.buscarPorId)
router.get('/:id/saude', saudeController.relatorioDaAluna)
router.post('/:id/registros-saude', saudeController.registrarRegistro)
router.delete('/:id/registros-saude/:registroId', saudeController.apagarRegistroDaAluna)
router.get('/:id/avaliacoes', saudeController.listarAvaliacoes)
router.post('/:id/avaliacoes', saudeController.registrarAvaliacao)
router.delete('/:id/avaliacoes/:avaliacaoId', saudeController.apagarAvaliacao)
router.get('/:id/niveis-natacao', natacaoController.listar)
router.post('/:id/niveis-natacao', natacaoController.registrar)
router.delete('/:id/niveis-natacao/:registroId', natacaoController.apagar)
router.post('/', usuarioController.criar)
router.patch('/:id', usuarioController.atualizar)
router.patch('/:id/senha', usuarioController.atualizarSenha)
router.delete('/:id', usuarioController.remover)

module.exports = router
